# Generated by Django 3.0 on 2020-02-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200214_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='choices',
            new_name='choice',
        ),
    ]
