# Generated by Django 3.0 on 2020-02-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200217_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='choice',
        ),
        migrations.AddField(
            model_name='voters',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
