# Generated by Django 3.0 on 2020-02-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200217_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
