# Generated by Django 3.0 on 2019-12-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_event_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Employee',
            new_name='employee',
        ),
    ]
